import { Meta, Link } from "@solidjs/meta";

export default function IconMeta() {
	return (
		<>
			<Meta
				name="mobile-web-app-capable"
				content="yes"
			/>
			<Meta
				name="apple-mobile-web-app-capable"
				content="yes"
			/>
			<Meta
				name="apple-mobile-web-app-status-bar-style"
				content="black"
			/>
			<Meta
				name="theme-color"
				content="#ff00ff"
			/>
			<Link
				rel="icon"
				type="image/png"
				href="/Icons/favicon@32.png"
			/>
			<Link
				rel="icon"
				sizes="192x192"
				href="/Icons/icon@192.png"
			/>
			<Link
				rel="apple-touch-icon"
				href="/Icons/icon@152.png"
			/>
			<Meta
				name="msapplication-square310x310logo"
				content="/Icons/icon@310.png"
			/>
			<Link
				rel="apple-touch-icon"
				href="/Icons/icon@310.png"
			/>
			<Link
				rel="apple-touch-icon"
				sizes="76x76"
				href="/Icons/icon@72.png"
			/>
			<Link
				rel="apple-touch-icon"
				sizes="120x120"
				href="/Icons/icon@128.png"
			/>
			<Link
				rel="apple-touch-icon"
				sizes="152x152"
				href="/Icons/icon@152.png"
			/>
			<Meta
				name="msapplication-square70x70logo"
				content="/Icons/icon@72.png"
			/>
			<Meta
				name="msapplication-square150x150logo"
				content="/Icons/icon@152.png"
			/>
			<Meta
				name="msapplication-wide310x150logo"
				content="/Icons/icon_widetile.png"
			/>
		</>
	);
}
